# GB0160

## Graph-Break Type
*Short name describing what triggered the graph break*
Unsupported next() call

## Context
*Values or code snippet captured at the break point*
next({self})

## Explanation
*Why this specific graph break happened*
Dynamo does not know how to trace calling `next()` on variable `{self}`.

## Hints
*Suggestions for fixing or working around the break*
- Dynamo has detected that tracing the code will result in an error when running in eager. Please double check that your code doesn't contain a similar error when actually running eager/uncompiled.



[Back to Registry](../index.md)
