# GB0133

## Graph-Break Type
*Short name describing what triggered the graph break*
Unsupported arguments for itertools.accumulate

## Context
*Values or code snippet captured at the break point*
call_function {self} {args} {kwargs}

## Explanation
*Why this specific graph break happened*
Dynamo does not know how to trace itertools.accumulate with args: {args} and kwargs: {kwargs}. itertools.accumulate expects an iterable, an optional binary function for accumulation, and an optional initial value to set the starting state.

## Hints
*Suggestions for fixing or working around the break*
- Make sure the arguments to itertools.accumulate are correct.
- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.



[Back to Registry](../index.md)
