# GB0168

## Graph-Break Type
*Short name describing what triggered the graph break*
Variadic function call with bad flags

## Context
*Values or code snippet captured at the break point*
flags: {inst.argval}

## Explanation
*Why this specific graph break happened*
Attempted to call a variadic function (CALL_FUNCTION_EX) with bad flags {inst.argval}

## Hints
*Suggestions for fixing or working around the break*
- This is likely to be a Dynamo bug. Please report an issue to PyTorch.



[Back to Registry](../index.md)
