---
layout: default
---
# GB0115

## Graph-Break Type
*Short name describing what triggered the graph break*

Unexpected failure during itertools.groupby() iteration

## Context
*Values or code snippet captured at the break point*

call_function {self} {args} {kwargs}

## Explanation
*Explanation of why the graph break was triggered*

Unexpected failure in invoking function during groupby

## Hints
*Hints on how to resolve the graph break*

- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->

[Back to Registry](../index.html)

[Edit this page on GitHub](https://github.com/pytorch-labs/compile-graph-break-site/edit/main/docs/gb/gb0115.md)
