---
layout: default
---
# GB0274

## Graph-Break Type
*Short name describing what triggered the graph break*

Attempted to reconstruct context manager's __enter__ method

## Context
*Values or code snippet captured at the break point*

str(self.ctx)

## Explanation
*Explanation of why the graph break was triggered*

Attempted to reconstruct context manager {type_str} while tracing `with ...:`

## Hints
*Hints on how to resolve the graph break*

- It is likely there is a graph break while tracing `with ctx:` 
- but outside the actual `ctx.__enter__()` method. 
- `torch.compile` does not expect this to happen.
- This is likely to be a Dynamo bug. Please report an issue to PyTorch.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/meta-pytorch/compile-graph-break-site/edit/main/docs/gb/gb0274.md)

[Back to Registry](../index.html)
