# GB0095

## Graph-Break Type
*Short name describing what triggered the graph break*
Set Exception object `__traceback__` attribute to not-`None`

## Context
*Values or code snippet captured at the break point*
call_setattr {self} {name}

## Explanation
*Why this specific graph break happened*
Dynamo does not support setting the attribute '__traceback__' on tracked exception objects to anything other than None.

## Hints
*Suggestions for fixing or working around the break*
- Avoid setting '__traceback__' on exception objects 
- within traced code, or set it to None.



[Back to Registry](../index.md)
