# GB0150

## Graph-Break Type
*Short name describing what triggered the graph break*
Unsupported hasattr call

## Context
*Values or code snippet captured at the break point*
call_obj_hasattr {self} {name}

## Explanation
*Why this specific graph break happened*
Dynamo does not know how to trace the function `{self.debug_repr()}`

## Hints
*Suggestions for fixing or working around the break*
- Avoid calling `hasattr({self.__class__.__name__}, {name})` in your code.
- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.



[Back to Registry](../index.md)
